<div class="container">
    <h3>Edit News</h3>
    <!-- Show Flash Session Data -->
    <p><?= $this->flashSession->output() ?></p>

    <?php
        # URL Segments
        $uri_segments = explode("/", $this->request->getUri());
    ?>
    <?= $this->tag->form("news/edit/submit"); ?>

        <div class="form-group">
            <label for="title">Article Title</label>
            <?= $form->render('title'); ?>
        </div>

        <div class="form-group">
            <label for="description">Article Description</label>
            <?= $form->render('description'); ?>
        </div>

        <div class="form-group">
            <?= $form->render('publish'); ?>
        </div>

        <?= $form->render('eid', ['value' => $uri_segments[4]]); ?>

        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
    <?= $this->tag->endForm() ?>
</div>
